#!/usr/bin/env bash
# Generate UUIDs, x25519 keypairs, short IDs and write them into .env
# between auto-managed markers. Re-running overwrites the previous block.
#
# Requires one of: xray in PATH (best), docker, podman.
set -euo pipefail

# Resolve repo root (this script sits at ansible/scripts/).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"

BEGIN_MARK="# === chain-proxy keys (auto-generated by make gen-keys; do not edit) ==="
END_MARK="# === end chain-proxy keys ==="

have() { command -v "$1" >/dev/null 2>&1; }

gen_uuid() {
  if   have uuidgen;  then uuidgen | tr '[:upper:]' '[:lower:]'
  elif have python3;  then python3 -c 'import uuid; print(uuid.uuid4())'
  else openssl rand -hex 16 | sed -E 's/(.{8})(.{4})(.{4})(.{4})(.{12})/\1-\2-\3-\4-\5/'
  fi
}

gen_sid() { openssl rand -hex 8; }

gen_x25519() {
  if   have xray;   then xray x25519
  elif have docker; then docker run --rm ghcr.io/xtls/xray-core:latest x25519
  elif have podman; then podman run --rm ghcr.io/xtls/xray-core:latest x25519
  else
    echo "ERROR: install xray, docker, or podman to generate x25519 keypairs." >&2
    echo "       macOS:  brew install xray" >&2
    echo "       Linux:  bash <(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh) install" >&2
    exit 1
  fi
}

# WireGuard keypairs: VPS1 ↔ VPS2 inter-VPS tunnel.
# Output two lines: "<private>\n<public>".
gen_wg() {
  local priv pub
  if have wg; then
    priv=$(wg genkey)
    pub=$(printf '%s' "$priv" | wg pubkey)
  elif have docker; then
    priv=$(docker run --rm --entrypoint sh linuxserver/wireguard:latest -c 'wg genkey')
    pub=$(docker run --rm --entrypoint sh linuxserver/wireguard:latest -c "echo '$priv' | wg pubkey")
  elif have podman; then
    priv=$(podman run --rm --entrypoint sh docker.io/linuxserver/wireguard:latest -c 'wg genkey')
    pub=$(podman run --rm --entrypoint sh docker.io/linuxserver/wireguard:latest -c "echo '$priv' | wg pubkey")
  else
    echo "ERROR: install wireguard-tools (or docker/podman) to generate WG keys." >&2
    echo "       macOS:  brew install wireguard-tools" >&2
    echo "       Linux:  sudo apt install wireguard-tools" >&2
    exit 1
  fi
  printf '%s\n%s\n' "$priv" "$pub"
}

parse_field() { awk -F': *' -v k="$1" 'tolower($1) ~ tolower(k) { print $2; exit }'; }

echo "Generating x25519 keypairs (entry + chain-link) ..." >&2
ENTRY_KEYS=$(gen_x25519)
LINK_KEYS=$(gen_x25519)

ENTRY_PRIV=$(printf '%s\n' "$ENTRY_KEYS" | parse_field 'private')
ENTRY_PUB=$( printf '%s\n' "$ENTRY_KEYS" | parse_field 'public')
LINK_PRIV=$( printf '%s\n' "$LINK_KEYS"  | parse_field 'private')
LINK_PUB=$(  printf '%s\n' "$LINK_KEYS"  | parse_field 'public')

echo "Generating WireGuard keypairs (VPS1 + VPS2) ..." >&2
WG_VPS1_KEYS=$(gen_wg)
WG_VPS2_KEYS=$(gen_wg)
WG_VPS1_PRIV=$(printf '%s\n' "$WG_VPS1_KEYS" | sed -n '1p')
WG_VPS1_PUB=$( printf '%s\n' "$WG_VPS1_KEYS" | sed -n '2p')
WG_VPS2_PRIV=$(printf '%s\n' "$WG_VPS2_KEYS" | sed -n '1p')
WG_VPS2_PUB=$( printf '%s\n' "$WG_VPS2_KEYS" | sed -n '2p')

ENTRY_UUID_VAL=$(gen_uuid)
ENTRY_FRIENDS_UUID_VAL=$(gen_uuid)
LINK_UUID_VAL=$(gen_uuid)
ENTRY_SID_VAL=$(gen_sid)
LINK_SID_VAL=$(gen_sid)

# Make sure .env exists (bootstrap from .env.example the first time).
if [ ! -f "$ENV_FILE" ]; then
  if [ -f "$ENV_EXAMPLE" ]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    echo "Created $ENV_FILE from .env.example (fill in IP_VPS1 and IP_VPS2)." >&2
  else
    : > "$ENV_FILE"
  fi
fi

# Strip any previous auto-generated block (between markers) from .env.
TMP_FILE="$ENV_FILE.tmp.$$"
awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
  BEGIN { skip = 0 }
  {
    if (!skip && index($0, b) == 1) { skip = 1; next }
    if ( skip && index($0, e) == 1) { skip = 0; next }
    if (!skip) print
  }
' "$ENV_FILE" > "$TMP_FILE"

# Trim trailing blank lines, then append fresh block.
awk 'BEGIN{RS=""; ORS=""} {print}' "$TMP_FILE" > "$ENV_FILE"
printf '\n\n%s\n' "$BEGIN_MARK"       >> "$ENV_FILE"
printf 'ENTRY_CLIENT_UUID=%s\n'  "$ENTRY_UUID_VAL"         >> "$ENV_FILE"
printf 'ENTRY_FRIENDS_UUID=%s\n' "$ENTRY_FRIENDS_UUID_VAL" >> "$ENV_FILE"
printf 'ENTRY_PRIVATE_KEY=%s\n'  "$ENTRY_PRIV"             >> "$ENV_FILE"
printf 'ENTRY_PUBLIC_KEY=%s\n'   "$ENTRY_PUB"              >> "$ENV_FILE"
printf 'ENTRY_SHORT_ID=%s\n'     "$ENTRY_SID_VAL"          >> "$ENV_FILE"
printf 'LINK_UUID=%s\n'         "$LINK_UUID_VAL" >> "$ENV_FILE"
printf 'LINK_PUBLIC_KEY=%s\n'   "$LINK_PUB"      >> "$ENV_FILE"
printf 'LINK_PRIVATE_KEY=%s\n'  "$LINK_PRIV"     >> "$ENV_FILE"
printf 'LINK_SHORT_ID=%s\n'     "$LINK_SID_VAL"  >> "$ENV_FILE"
printf 'WG_VPS1_PRIVATE=%s\n'   "$WG_VPS1_PRIV"  >> "$ENV_FILE"
printf 'WG_VPS1_PUBLIC=%s\n'    "$WG_VPS1_PUB"   >> "$ENV_FILE"
printf 'WG_VPS2_PRIVATE=%s\n'   "$WG_VPS2_PRIV"  >> "$ENV_FILE"
printf 'WG_VPS2_PUBLIC=%s\n'    "$WG_VPS2_PUB"   >> "$ENV_FILE"
printf '%s\n' "$END_MARK"                        >> "$ENV_FILE"
rm -f "$TMP_FILE"

# Determine client-facing VPS1 IP for the VLESS URI preview.
VPS1_IP="${IP_VPS1:-}"
if [ -z "$VPS1_IP" ] && [ -f "$ENV_FILE" ]; then
  VPS1_IP=$(awk -F= '/^IP_VPS1=/ {print $2; exit}' "$ENV_FILE")
fi
[ -z "$VPS1_IP" ] && VPS1_IP='<VPS1_IP>'

cat >&2 <<EOF

✓ Keys generated and written to $ENV_FILE
  (block between '$BEGIN_MARK' and '$END_MARK')

  Ansible will read them automatically on the next \`make deploy\`.
  You don't need to touch group_vars/*.yml — the values are pulled from env.

─── client VLESS URI: admin (paste into Amnezia / v2rayN / NekoBox) ─────
vless://$ENTRY_UUID_VAL@$VPS1_IP:443?type=tcp&security=reality&pbk=$ENTRY_PUB&fp=chrome&sni=www.microsoft.com&sid=$ENTRY_SID_VAL&flow=xtls-rprx-vision#chain-ru-admin

─── client VLESS URI: friends ───────────────────────────────────────────
vless://$ENTRY_FRIENDS_UUID_VAL@$VPS1_IP:443?type=tcp&security=reality&pbk=$ENTRY_PUB&fp=chrome&sni=www.microsoft.com&sid=$ENTRY_SID_VAL&flow=xtls-rprx-vision#chain-ru-friends

EOF
