---
- name: Converge
  hosts: all
  become: true
  vars:
    firewall_enabled: true
    firewall_allowed_tcp_ports:
      - 22
      - 443
      - 8443
    firewall_allowed_udp_ports:
      - 51820
  roles:
    - role: common
